version: '3.7'

services:
  bastyon-chat:
    container_name: 'bastyon-chat'
    image: pocketnetteam/matrix-synapse:latest
    environment:
    - SYNAPSE_REPORT_STATS=no
    - SYNAPSE_SERVER_NAME=#DOMAIN
    volumes:
      - ./data:/data
      - ./configs:/configs
    ports:
      - "#PORT:8008"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"