version: '3.7'

services:
  bastyon-chat:
    container_name: 'bastyon-chat'
    image: pocketnetteam/matrix-synapse:latest
    environment:
    - SYNAPSE_REPORT_STATS=no
    - SYNAPSE_SERVER_NAME=#DOMAIN
    volumes:
      - ./data:/data
      - ./configs:/configs
    ports:
      - "8009:8008"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"

  bastyon-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
#      - ./configs/nginx/main.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"

  bastyon-certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./configs/certbot/conf:/etc/letsencrypt
      - ./configs/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"